branches:
  only:
    - development/r1.0
    - release/r1.0

language: generic

addons:
  apt:
    sources:
    - sourceline: "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main"
      key_url: 
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      env:
        - HTTPLEASE_BUILD_VERSION="beta3"
        - DOTNET_SDK_URL=https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh
      install:
        - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
        - echo "$DOTNET_INSTALL_DIR"
        - mkdir -p "$DOTNET_INSTALL_DIR"
        - curl -L "$DOTNET_SDK_URL" | bash
        - export PATH="$DOTNET_INSTALL_DIR:$PATH"

    - os: osx # OSX 10.11
      osx_image: xcode7.2
      env:
        - HTTPLEASE_BUILD_VERSION="beta3"
        - DOTNET_SDK_URL=https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh
      before_install:
        - brew update
        - brew install openssl
        - ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
        - ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
      install:
        - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
        - echo "$DOTNET_INSTALL_DIR"
        - mkdir -p "$DOTNET_INSTALL_DIR"
        - curl -L "$DOTNET_SDK_URL" | bash
        - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - dotnet --info
  - echo 'dotnet restore' && echo -en 'travis_fold:start:dotnet_restore'
  - dotnet restore
  - echo -en 'travis_fold:end:dotnet_restore'
  - echo 'dotnet build' && echo -en 'travis_fold:start:dotnet_build'
  - dotnet build "src/HTTPlease*/project.json" "test/HTTPlease.*Tests*/project.json"
  - echo -en 'travis_fold:end:dotnet_build'
  - echo 'dotnet build' && echo -en 'travis_fold:start:dotnet_test'
  - for PRJ in $(ls -d test/HTTPlease.*Tests); do dotnet test $PRJ; done
  - echo -en 'travis_fold:end:dotnet_test'
  - echo 'dotnet pack' && echo -en 'travis_fold:start:dotnet_pack'
  - for PRJ in $(ls -d test/HTTPlease.*Tests); do dotnet pack $PRJ; done
  - echo -en 'travis_fold:end:dotnet_pack'
